<a href="https://colab.research.google.com/github/yasiruKodikara/DeepLearning-Specialization-stanford-online/blob/main/broadcasting_in_python_C1W2L16.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
A = np.array([
    [56.0,0.0,4.4,68.0],
    [1.2,104.0,52.0,8.0],
    [1.8,135.0,99.0,0.9]
])

In [ ]:
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [ ]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [ ]:
perc = 100*A/cal
print(perc)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]
