<a href="https://colab.research.google.com/github/yasiruKodikara/DeepLearning-Specialization-stanford-online/blob/main/python_numpy_vectors_C1W2L17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
a = np.random.randn(5)

In [3]:
print(a)

[-0.59401775  0.51400176  0.75240613 -0.88071944 -0.06581327]


In [4]:
print(a.shape)

(5,)


In [5]:
print(a.T)

[-0.59401775  0.51400176  0.75240613 -0.88071944 -0.06581327]


In [6]:
a.reshape(5,1)

array([[-0.59401775],
       [ 0.51400176],
       [ 0.75240613],
       [-0.88071944],
       [-0.06581327]])

In [7]:
print(a.T)

[-0.59401775  0.51400176  0.75240613 -0.88071944 -0.06581327]
